services:
  app:
    build: .
    container_name: synergazing-app-prod
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    networks:
      - caddy_net_external
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: 128M
    volumes:
      - backend-storage-prod:/root/storage
  db:
    image: postgres:15-alpine
    command: postgres -c 'shared_buffers=64MB' -c 'max_connections=50'
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M
    container_name: synergazing-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net

volumes:
  postgres-data-prod:
  backend-storage-prod: