services:
  app:
    build: .
    container_name: synergazing-app-dev
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    networks:
      - caddy_net_external
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.20'
    #       memory: 80M
    volumes:
      - backend-storage-dev:/root/storage

  db:
    image: postgres:15-alpine
    command: postgres -c 'shared_buffers=24MB' -c 'max_connections=20'
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.30'
    #       memory: 256M
    container_name: synergazing-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net

volumes:
  postgres-data-dev:
  backend-storage-dev: