services:
  app:
    build: .
    container_name: synergazing-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:3002"
    env_file: .env
    depends_on:
      - db
    networks:
      - caddy_net_external

  db:
    image: postgres:15-alpine
    container_name: synergazing-db 
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net

volumes:
  postgres-data: