services:
  app:
    build: .
    container_name: synergazing-app-dev
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    networks:
      - caddy_net_external
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  db:
    image: postgres:15-alpine
    container_name: synergazing-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - caddy_net_external

networks:
  caddy_net_external:
    external: true
    name: caddy_net

volumes:
  postgres-data-dev: